### ISSUE TITLE
License question 

### ISSUE THREAD

**Issue by uni-dos** [MrSinho/shvulkan#1]
Why was GPL used? I think the LGPL would have been a better choice.

**Comment by MrSinho** [comment]
I went for the most used _copyleft_ licence for open source projects. When it comes with choosing between GPL and LGPL I believe that the LGPL won't make the library more suitable for its purposes. Why do you think the LGPL license is a better choice?

**Comment by uni-dos** [comment]
From what I understand about the GPL, if I use your code in my project, then I myself will have to release my code under that too. If it were licensed under LGPL, I can release my code under my license but the library will be left unmodified. 

Or you could add a linking exception like [libgit2](https://github.com/libgit2/libgit2#license) did. But then again, IANAL/IANYL.

**Comment by MrSinho** [comment]
This is intended to be a way to "protect" the library from being used in proprietary programs, which are in contrast with the open source belief. I am not a lawyer too and my understanding of copyright and software licenses is very limited, but for now I think I'll keep this license, but things may change in the future.

Quote the license made by the Free Software Foundation:
> [...] the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.  We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your programs, too.

**Comment by MrSinho** [comment]
This is intended to be a way to "protect" the library from being used in proprietary programs, which use more restrictive licenses but rely on open source code. I am not a lawyer too and my understanding of copyright and software licenses is still very limited. For now I think I'll keep this license, but things may change in the future.

Quote the license made by the Free Software Foundation:

> [...] the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users. We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors. You can apply it to
your programs, too.

**Comment by uni-dos** [comment]
I understand and respect your choice. I'll close the issue.
